"""
IFL Cards – build.py
====================
Reads packs/packs.csv and each pack's cards.csv,
writes packs.js so index.html works locally without a server.

Run after editing any CSV:
    python build.py

packs/packs.csv columns:     id, name, sub
packs/<id>/cards.csv columns: file, name, team, league, teamCode, rarity, landscape, position
  rarity:    c (common) | u (uncommon) | r (rare) | sr (secret rare)
  landscape: true | false
  position:  QB, WR, RB, DB, etc (optional)
"""

import csv, json, os

BASE      = os.path.dirname(os.path.abspath(__file__))
PACKS_DIR = os.path.join(BASE, 'packs')
META_CSV  = os.path.join(PACKS_DIR, 'packs.csv')
OUT_JS    = os.path.join(BASE, 'packs.js')

def read_csv(path):
    if not os.path.exists(path):
        return []
    with open(path, newline='', encoding='utf-8-sig') as f:
        return list(csv.DictReader(f))

def build():
    meta_rows = read_csv(META_CSV)
    if not meta_rows:
        print(f'ERROR: could not read {META_CSV}')
        return

    packs = []
    for m in meta_rows:
        pid = m['id'].strip()
        rows = read_csv(os.path.join(PACKS_DIR, pid, 'cards.csv'))
        cards = []
        for r in rows:
            f = r.get('file','').strip()
            if not f:
                continue
            cards.append({
                'file':      f,
                'name':      r.get('name','').strip(),
                'team':      r.get('team','').strip(),
                'league':    r.get('league','').strip(),
                'teamCode':  r.get('teamCode','').strip(),
                'rarity':    r.get('rarity','c').strip().lower(),
                'landscape': r.get('landscape','false').strip().lower() == 'true',
                'position':  r.get('position','').strip(),
                'order':     int(r.get('order','').strip()) if r.get('order','').strip().isdigit() else 9999,
                'back':      r.get('back','').strip(),
                'qty':       int(r.get('qty','').strip()) if r.get('qty','').strip().isdigit() else None,
            })
        packs.append({'id': pid, 'name': m.get('name',pid).strip(),
                      'sub': m.get('sub','').strip(), 'cards': cards})
        print(f'  {pid}: {len(cards)} card(s)')

    js  = '// AUTO-GENERATED by build.py — do not edit this file directly.\n'
    js += '// Edit packs/packs.csv and packs/<PackID>/cards.csv then run:  python build.py\n'
    js += 'var PACK_DATA = ' + json.dumps(packs, indent=2) + ';\n'

    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write(js)
    print(f'\nWrote packs.js  ({len(packs)} pack(s) total)')

if __name__ == '__main__':
    print('Building packs.js ...')
    build()
