// AUTO-GENERATED by build.py — do not edit this file directly.
// Edit packs/packs.csv and packs/<PackID>/cards.csv then run:  python build.py
var PACK_DATA = [
  {
    "id": "IFL2025",
    "name": "IFL 2025",
    "sub": "Indoor Football League \u00b7 2025 Season",
    "cards": [
      {
        "file": "LowellPatronGB_r.png",
        "name": "Lowell Patron Jr.",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "r",
        "landscape": false,
        "position": "WR"
      },
      {
        "file": "CameronHarrelQC_c.png",
        "name": "Cameron Harrell",
        "team": "Quad City Steamwheelers",
        "league": "IFL",
        "teamCode": "QC",
        "rarity": "c",
        "landscape": false,
        "position": "DB"
      },
      {
        "file": "HarryBallardGB_c.png",
        "name": "Harry Ballard III",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "c",
        "landscape": false,
        "position": "WR"
      },
      {
        "file": "RaymondBooneGB_c.png",
        "name": "Raymond Boone",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "c",
        "landscape": false,
        "position": "DB"
      },
      {
        "file": "AndrewCarterSR.png",
        "name": "Andrew Carter",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "sr",
        "landscape": false,
        "position": "OL"
      },
      {
        "file": "HarryBallardGB_u.png",
        "name": "Harry Ballard III",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "u",
        "landscape": false,
        "position": "WR"
      },
      {
        "file": "boodahlewis_u.png",
        "name": "Zane Lewis",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "u",
        "landscape": false,
        "position": "WR"
      }
    ]
  },
  {
    "id": "AFLAllEras",
    "name": "AFL All Eras",
    "sub": "Arena Football League \u00b7 All-Time Greats",
    "cards": []
  },
  {
    "id": "AFLLegends",
    "name": "AFL Legends",
    "sub": "Arena Football League \u00b7 Legends",
    "cards": []
  }
];
