// AUTO-GENERATED by build.py — do not edit this file directly.
// Edit packs/packs.csv and packs/<PackID>/cards.csv then run:  python build.py
var PACK_DATA = [
  {
    "id": "IFL2025",
    "name": "IFL 2025",
    "sub": "Indoor Football League \u00b7 2025 Season",
    "cards": [
      {
        "file": "CameronHarrelQC_c.png",
        "name": "Cameron Harrell",
        "team": "Quad City Steamwheelers",
        "league": "IFL",
        "teamCode": "QC",
        "rarity": "c",
        "landscape": false,
        "position": "DB",
        "order": 1
      },
      {
        "file": "HarryBallardGB_c.png",
        "name": "Harry Ballard III",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "c",
        "landscape": false,
        "position": "WR",
        "order": 2
      },
      {
        "file": "RaymondBooneGB_c.png",
        "name": "Raymond Boone",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "c",
        "landscape": false,
        "position": "DB",
        "order": 3
      },
      {
        "file": "CameronHarrelQC_c.png",
        "name": "Cameron Harrell",
        "team": "Quad City Steamwheelers",
        "league": "IFL",
        "teamCode": "QC",
        "rarity": "u",
        "landscape": false,
        "position": "DB",
        "order": 4
      },
      {
        "file": "HarryBallardGB_c.png",
        "name": "Harry Ballard III",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "u",
        "landscape": false,
        "position": "WR",
        "order": 5
      },
      {
        "file": "HarryBallardGB_u.png",
        "name": "Harry Ballard III",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "u",
        "landscape": false,
        "position": "WR",
        "order": 7
      },
      {
        "file": "RaymondBooneGB_c.png",
        "name": "Raymond Boone",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "u",
        "landscape": false,
        "position": "DB",
        "order": 6
      },
      {
        "file": "boodahlewis_u.png",
        "name": "Zane Lewis",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "u",
        "landscape": false,
        "position": "WR",
        "order": 8
      },
      {
        "file": "CameronHarrelQC_c.png",
        "name": "Cameron Harrell",
        "team": "Quad City Steamwheelers",
        "league": "IFL",
        "teamCode": "QC",
        "rarity": "r",
        "landscape": false,
        "position": "DB",
        "order": 9
      },
      {
        "file": "HarryBallardGB_c.png",
        "name": "Harry Ballard III",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "r",
        "landscape": false,
        "position": "WR",
        "order": 10
      },
      {
        "file": "LowellPatronGB_r.png",
        "name": "Lowell Patron Jr.",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "r",
        "landscape": false,
        "position": "WR",
        "order": 12
      },
      {
        "file": "RaymondBooneGB_c.png",
        "name": "Raymond Boone",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "r",
        "landscape": false,
        "position": "DB",
        "order": 11
      },
      {
        "file": "AndrewCarterSR.png",
        "name": "Andrew Carter",
        "team": "Green Bay Blizzard",
        "league": "IFL",
        "teamCode": "GB",
        "rarity": "sr",
        "landscape": false,
        "position": "OL",
        "order": 13
      }
    ]
  },
  {
    "id": "AFLAllEras",
    "name": "AFL All Eras",
    "sub": "Arena Football League \u00b7 All-Time Greats",
    "cards": []
  },
  {
    "id": "AFLLegends",
    "name": "AFL Legends",
    "sub": "Arena Football League \u00b7 Legends",
    "cards": [
      {
        "file": "AaronGarcia_c.png",
        "name": "Aaron Garcia",
        "team": "New York Dragons",
        "league": "AFL",
        "teamCode": "NYD",
        "rarity": "c",
        "landscape": false,
        "position": "QB",
        "order": 1
      },
      {
        "file": "MikeWashington_c.png",
        "name": "Mike Washington",
        "team": "Pittsburgh Power",
        "league": "AFL",
        "teamCode": "PIT",
        "rarity": "c",
        "landscape": false,
        "position": "WR",
        "order": 2
      },
      {
        "file": "Bones_u.png",
        "name": "Bones - Mascot",
        "team": "New Orleans VooDoo",
        "league": "AFL",
        "teamCode": "NOV",
        "rarity": "u",
        "landscape": false,
        "position": "Mascot",
        "order": 5
      },
      {
        "file": "Stryker_u.png",
        "name": "Stryker - Mascot",
        "team": "Arizona Rattlers",
        "league": "AFL",
        "teamCode": "ARZ",
        "rarity": "u",
        "landscape": false,
        "position": "Mascot",
        "order": 7
      },
      {
        "file": "Aaron_Garcia_r.png",
        "name": "Aaron Garcia - MVP",
        "team": "Jacksonville Sharks",
        "league": "AFL",
        "teamCode": "JAX",
        "rarity": "r",
        "landscape": false,
        "position": "QB",
        "order": 8
      },
      {
        "file": "BobMcMillen_r.png",
        "name": "Bob McMillen - COVER ART",
        "team": "Chicago Rush",
        "league": "AFL",
        "teamCode": "CHI",
        "rarity": "r",
        "landscape": false,
        "position": "FB/LB",
        "order": 9
      },
      {
        "file": "MikeWashington_r.png",
        "name": "Mike \"The Joystick\" Washington",
        "team": "Pittsburgh Power",
        "league": "AFL",
        "teamCode": "POW",
        "rarity": "r",
        "landscape": false,
        "position": "WR",
        "order": 10
      },
      {
        "file": "SoulMan_u.png",
        "name": "Soul Man",
        "team": "Philadelphia Soul",
        "league": "AFL",
        "teamCode": "PHI",
        "rarity": "u",
        "landscape": false,
        "position": "Mascot",
        "order": 6
      },
      {
        "file": "AaronGarcia_c.png",
        "name": "Aaron Garcia",
        "team": "New York Dragons",
        "league": "AFL",
        "teamCode": "NYD",
        "rarity": "u",
        "landscape": false,
        "position": "QB",
        "order": 3
      },
      {
        "file": "MikeWashington_c.png",
        "name": "Mike Washington",
        "team": "Pittsburgh Power",
        "league": "AFL",
        "teamCode": "PIT",
        "rarity": "u",
        "landscape": false,
        "position": "WR",
        "order": 4
      },
      {
        "file": "AaronGarcia_c.png",
        "name": "Aaron Garcia",
        "team": "New York Dragons",
        "league": "AFL",
        "teamCode": "NYD",
        "rarity": "r",
        "landscape": false,
        "position": "QB",
        "order": 12
      },
      {
        "file": "MikeWashington_c.png",
        "name": "Mike Washington",
        "team": "Pittsburgh Power",
        "league": "AFL",
        "teamCode": "PIT",
        "rarity": "r",
        "landscape": false,
        "position": "WR",
        "order": 11
      }
    ]
  }
];
